# Generated by Django 5.1.1 on 2024-10-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amound_paid',
            new_name='amount_paid',
        ),
    ]
